# Generated by Django 5.2.1 on 2025-05-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_app', '0003_remove_feedbackresponse_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='user',
            new_name='customer',
        ),
    ]
